html-forms - Lawrence Wang
wang-lawrence/c0523-code-solutions pull request #29
Opened 2023-05-15 22:14 UTC by wang-lawrence

<img width="367" alt="Screen Shot 2023-05-15 at 3 12 44 PM" src="https://github.com/wang-lawrence/c0523-code-solutions/assets/130196412/3a0f6e85-6fc7-49d4-bfae-fe162fc5b793">

2023-05-15 22:27 UTC, shawnkost requested changes
A few changes here Lawrence!

2023-05-15 22:27 UTC, shawnkost commented on html-forms/index.html
> +     </label>
If you're going to put the `input` inside the `label`, then the `for` attribute isn't needed. It's either use the `for` attribute OR nest the `input` inside the `label`

2023-05-15 22:27 UTC, shawnkost commented on html-forms/index.html
> +     </label>
Same note as above ^

2023-05-15 22:27 UTC, shawnkost commented on html-forms/index.html
> +     </label>
`label` elements need to have some text associated with it. Your text inside your `div` on line 10, should go inside this `label`

2023-05-15 22:27 UTC, shawnkost commented on html-forms/index.html
> +     </label>
`label` needs to have some text associated with it. Utilize your text content inside your `div` above this

2023-05-15 22:27 UTC, shawnkost commented on html-forms/index.html
> +        </label>
If you're going to put the `input` inside the `label`, then the `for` attribute isn't needed. It's either use the `for` attribute OR nest the `input` inside the `label`

2023-05-15 22:27 UTC, shawnkost commented on html-forms/index.html
> +      </label>
`label` needs to have some text associated with it. Utilize your text content inside the `div` on line 43

2023-05-15 23:12 UTC, wang-lawrence commented
Thanks Shawn. I think going forward I will try to not nest them. On FCC they tend to nest <input> in the <label> elements, but still still had the "for" attribute in the <label>. Is there any benefit to doing that?
<img width="639" alt="image" src="https://github.com/wang-lawrence/c0523-code-solutions/assets/130196412/821a8ae0-0a30-408c-9961-3f85b23b26e8">

2023-05-16 15:27 UTC, shawnkost approved these changes
Approved. To answer your question, there's no advantage of doing both at the same time. It's unnecessary, it's either one or the other. Not sure why they do that on their site.

2023-05-16 16:18 UTC, merged