css-layout-classes - Lawrence Wang
wang-lawrence/c0523-code-solutions pull request #39
Opened 2023-05-18 06:04 UTC by wang-lawrence

<img width="565" alt="Screen Shot 2023-05-17 at 10 53 19 PM" src="https://github.com/wang-lawrence/c0523-code-solutions/assets/130196412/f7bf12c7-a6f6-4d38-90c9-3a281d34cded">

I have a couple of questions on this exercise. 
1. Without setting the image to 100% width, the row with 4 images overflowed. I thought setting the flex-basis = 25% would shrink the images so they fit into the container, why didn't it? Should we always set images to width to 100% just to be safe?
<img width="750" alt="Screen Shot 2023-05-17 at 9 37 42 PM" src="https://github.com/wang-lawrence/c0523-code-solutions/assets/130196412/0b8f7ef0-de07-496a-8ba3-b1d580258d6b">
2. I shrunk the images on the row with four images. I then tried to center them by selecting the column-fourth class (the div's that contain each image) and setting justify-content: center, but the images didn't move. How would I go about centering these images?

<img width="560" alt="Screen Shot 2023-05-17 at 10 03 57 PM" src="https://github.com/wang-lawrence/c0523-code-solutions/assets/130196412/d6485c0c-f420-44cb-8b95-1dfe5c984284">

2023-05-18 17:09 UTC, wang-lawrence commented
You've actually answered all my questions in class so we're good!

2023-05-18 17:12 UTC, shawnkost requested changes
Some changes requested here Lawrence!

2023-05-18 17:12 UTC, shawnkost commented on css-layout-classes/index.html
> +    <h1>Choose your character!</h1>
This should be inside a `row` & a `column-full`

2023-05-18 17:12 UTC, shawnkost commented on css-layout-classes/index.html
> +      <div class="link-image">
This should be named more appropriately like `column-third`

2023-05-18 17:12 UTC, shawnkost commented on css-layout-classes/index.html
> +      <div class="ssb-text">
This should be named more appropriately like `column-third`

2023-05-18 17:12 UTC, shawnkost commented on css-layout-classes/index.html
> +      <div class="yoshi-image">
This should be named more appropriately like `column-third`

2023-05-18 17:12 UTC, shawnkost commented on css-layout-classes/index.html
> +      <div class="dk-text">
This should be named more appropriately like `column-two-thirds`

2023-05-18 17:12 UTC, shawnkost commented on css-layout-classes/index.html
> +      <div class="dk-image">
This should be named more appropriately like `column-third`

2023-05-18 17:12 UTC, shawnkost commented on css-layout-classes/index.html
> +      <div class="mario-image">
This should be named more appropriately like `column-third`

2023-05-18 17:12 UTC, shawnkost commented on css-layout-classes/index.html
> +      <div class = "mario-text">
This should be named more appropriately like `column-two-thirds`

2023-05-18 17:12 UTC, shawnkost commented on css-layout-classes/styles.css
> +
Once you adjust your class names, you'll need to adjust the css. You should have more column selectors here. Compare against the solution I posted in the main class channel

2023-05-19 19:10 UTC, shawnkost approved these changes
👍🏻

2023-05-22 07:54 UTC, merged