react-accordion-component - Lawrence Wang
wang-lawrence/c0523-code-solutions pull request #91
Opened 2023-06-29 23:48 UTC by wang-lawrence

https://github.com/wang-lawrence/c0523-code-solutions/assets/130196412/57157706-a319-4625-927a-5b98faa24e1a

2023-07-06 19:13 UTC, RobertGardner requested changes
You need to remove the use of getAttribute.

2023-07-06 19:13 UTC, RobertGardner commented on react-accordion-component/my-app/src/Accordion.jsx
> +export default function Accordiion({data}) {
Funny misspelling.

2023-07-06 19:13 UTC, RobertGardner commented on react-accordion-component/my-app/src/Accordion.jsx
> +  const [showDesc, setShowDesc] = useState(true);
Using 2 state variables isn't bad, but you could, if you wanted, get by with just one: use `id === undefined` to indicate that the description should not be shown.

2023-07-06 19:13 UTC, RobertGardner commented on react-accordion-component/my-app/src/Accordion.jsx
> +      <div>
This is duplicated from above on line 20. It would be better to remove the duplication and use conditional rendering only on the Description.

2023-07-06 19:13 UTC, RobertGardner commented on react-accordion-component/my-app/src/Accordion.jsx
> +      onClick={e => onToggle(+e.target.getAttribute('id'))}>
Yikes! Don't use `getAttribute` in React code! Why don't you just pass `keyId` to `onToggle`?

2023-07-07 17:48 UTC, wang-lawrence commented
Thanks for the tip of using `id===undefined`, that's clever and I wouldn't have been able to think of that.

2023-07-07 18:03 UTC, RobertGardner approved these changes

2023-07-07 18:03 UTC, merged